name=STM32duino LSM6DSO32
version=1.0.0
author=Nathan Garnier
maintainer=Nathan Garnier
sentence=Ultra Low Power inertial measurement unit.
paragraph=This library provides Arduino support for the Ultra Low Power LSM6DSO32 sensor.
category=Sensors
url=https://github.com/stm32duino/LSM6DSO32
architectures=*
